apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: urunc-deploy
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["create", "delete", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "delete"]
