apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: urunc-deploy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: urunc-deploy
subjects:
  - kind: ServiceAccount
    name: urunc-deploy
    namespace: kube-system